// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1PIE_4bHWA07zjfpwSy6XKNbW1rhQET0',
    appId: '1:486181838197:web:7c39fab63868350e2fc73c',
    messagingSenderId: '486181838197',
    projectId: 'authenticator-500d2',
    authDomain: 'authenticator-500d2.firebaseapp.com',
    storageBucket: 'authenticator-500d2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5KNKA8wh5lIntIhi5Hs7pPgXcHmlospk',
    appId: '1:486181838197:android:700163d4cf35a2ff2fc73c',
    messagingSenderId: '486181838197',
    projectId: 'authenticator-500d2',
    storageBucket: 'authenticator-500d2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqUdgcO15TBNi_7uUpHf0S63niwavTMlA',
    appId: '1:486181838197:ios:667a89e38f7e95b82fc73c',
    messagingSenderId: '486181838197',
    projectId: 'authenticator-500d2',
    storageBucket: 'authenticator-500d2.appspot.com',
    iosBundleId: 'com.example.authentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqUdgcO15TBNi_7uUpHf0S63niwavTMlA',
    appId: '1:486181838197:ios:667a89e38f7e95b82fc73c',
    messagingSenderId: '486181838197',
    projectId: 'authenticator-500d2',
    storageBucket: 'authenticator-500d2.appspot.com',
    iosBundleId: 'com.example.authentication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1PIE_4bHWA07zjfpwSy6XKNbW1rhQET0',
    appId: '1:486181838197:web:629ab765a3dfcc232fc73c',
    messagingSenderId: '486181838197',
    projectId: 'authenticator-500d2',
    authDomain: 'authenticator-500d2.firebaseapp.com',
    storageBucket: 'authenticator-500d2.appspot.com',
  );

}